### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'snap/pretrain/VLT5-novqa/Epoch30_base.pth'

### ISSUE THREAD

**Issue by alice-cool** [jingjing12110/MixPHM#3]
FileNotFoundError: [Errno 2] No such file or directory: 'snap/pretrain/VLT5-novqa/Epoch30_base.pth'

**Comment by jingjing12110** [comment]
Please download the pretrained weight from [FewVLM](https://drive.google.com/file/d/17B-3TcXJ1tumNPYAQpg2MisSi9-7Dz-Y/view?usp=sharing) and save them under the VLT5-novqa folder.

**Comment by alice-cool** [comment]
Thank you for your quick reply.



---Original---
From: "JJ ***@***.***&gt;
Date: Fri, Dec 8, 2023 12:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jingjing12110/MixPHM] FileNotFoundError: [Errno 2] No such fileor directory: 'snap/pretrain/VLT5-novqa/Epoch30_base.pth' (Issue #3)




 
Please download the pretrained weight from FewVLM and save them under the VLT5-novqa folder.
